<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "macro://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
    <dict>
        <key>scopeName</key>
        <string>source.macro</string>
        <key>fileTypes</key>
        <array>
            <string>macro</string>
        </array>
        <key>name</key>
        <string>macro</string>
        <key>patterns</key>
        <array>
            <dict>
                <key>match</key>
                <string>^\s*#{1,}\s*(((@)name)\s+(\S+))?.*$</string>
                <key>captures</key>
                <dict>
                    <key>2</key>
                    <dict>
                        <key>name</key>
                        <string>storage.type.class.metadata</string>
                    </dict>
                    <key>3</key>
                    <dict>
                        <key>name</key>
                        <string>punctuation.definition.block.tag.metadata</string>
                    </dict>
                    <key>4</key>
                    <dict>
                        <key>name</key>
                        <string>entity.name.type.instance.metadata</string>
                    </dict>
                </dict>
                <key>name</key>
                <string>comment.source.sharp.macro</string>
            </dict>
            <dict>
                <key>match</key>
                <string>^\s*/{2,}\s*(((@)name)\s+(\S+))?.*$</string>
                <key>captures</key>
                <dict>
                    <key>2</key>
                    <dict>
                        <key>name</key>
                        <string>storage.type.class.metadata</string>
                    </dict>
                    <key>3</key>
                    <dict>
                        <key>name</key>
                        <string>punctuation.definition.block.tag.metadata</string>
                    </dict>
                    <key>4</key>
                    <dict>
                        <key>name</key>
                        <string>entity.name.type.instance.metadata</string>
                    </dict>
                </dict>
                <key>name</key>
                <string>comment.source.double-slash.macro</string>
            </dict>
            <dict>
                <key>captures</key>
                <dict>
                    <key>1</key>
                    <dict>
                        <key>name</key>
                        <string>keyword.control.macro</string>
                    </dict>
                    <key>3</key>
                    <dict>
                        <key>name</key>
                        <string>constant.language.macro</string>
                    </dict>
                </dict>
                <key>match</key>
                <string>^(v|m|c|s|t|x)(\s)*(.*$)</string>
                <key>name</key>
                <string>macro.command</string>
            </dict>
        </array>
    </dict>
</plist>